### PR TITLE
More readable search results

### PR DESCRIPTION
**Pull request by arizonagroovejet**

### CODE REVIEW

**Comment by arizonagroovejet** [comment]
This Pull Request seems to also contain changes from #124  :/ Have I got my branches in a twist and messed this up?

**Comment by edent** [comment]
Ha! Probably. I often do. I'll take a look tomorrow 😁

**Comment by arizonagroovejet** [comment]
So is this PR viable or do I need to work out how to bin it then do another one with only then "More readable search results" commit in it?

**Comment by edent** [comment]
It's viable. I just spent the weekend drunk for tax purposes.

**Comment by arizonagroovejet** [comment]
Cool. I hope you had lots of hot black coffee to help you sober up. ;)

**Pull request merged**
