### PR TITLE
Add button to take the user to a random bench

### PR DESCRIPTION
**Pull request by mrwilson**
- Button on the front-page next to 'Show benches near me'.
- SQL query to pick a bench at random from the database.
- If "random" is present as a query param, load a random bench.

This addresses #40

### CODE REVIEW

**Comment by mrwilson** [comment]
No problem, both of those points make sense.

**Comment by edent** [comment]
Looks great! I'll test it tonight.

**Comment by edent** [comment]
Excellent. I've moved the button to the bottom of the screen. I've also fiddled with the cache on the redirect. Sadly, if you hit back then click Random again, you may get the same bench twice. Not sure if that is fixable.

Thank you once again!

Fixes #40

**Comment by andylolz** [comment]
Dropped by to say: this is a lovely feature on a lovely website.

Thanks, @mrwilson and @edent!

**Pull request merged**
